#!/usr/bin/env python3
"""Create full blueprint fixtures for PPT Native Composer regression testing."""

from __future__ import annotations

import argparse
import json
from copy import deepcopy
from pathlib import Path
from typing import Any


SKILL_DIR = Path(__file__).resolve().parents[1]
STYLE_LIBRARY = SKILL_DIR / "templates" / "style_packs" / "style_packs.json"


def load_style_pack(key: str) -> dict[str, Any]:
    payload = json.loads(STYLE_LIBRARY.read_text(encoding="utf-8"))
    packs = payload.get("style_packs", {})
    if key not in packs:
        raise SystemExit(f"Unknown style pack: {key}")
    return deepcopy(packs[key])


def visual_bible(style_pack: dict[str, Any]) -> dict[str, Any]:
    pal = style_pack.get("palette", {})
    return {
        "moodboard_reference": style_pack.get("reference_summary", ""),
        "style_direction": style_pack.get("quality_bar", ""),
        "design_tokens": {
            "colors": [
                pal.get("ink", "#111111"),
                pal.get("background", "#F7F3EC"),
                pal.get("accent", "#FF5A3D"),
                pal.get("secondary_accent", "#276EF1"),
                pal.get("muted", "#6E6A63"),
            ],
            "typography_tone": style_pack.get("typography", {}).get("title_character", ""),
            "shape_language": style_pack.get("composition_grammar", {}).get("grid", ""),
            "texture": style_pack.get("image_language", {}).get("texture", ""),
            "lighting": style_pack.get("image_language", {}).get("lighting", ""),
            "layout_density": style_pack.get("composition_grammar", {}).get("density_rule", ""),
        },
        "visual_motifs": style_pack.get("visual_motifs", []),
        "page_family_map": style_pack.get("page_families", {}),
        "asset_prompt_kit": {
            "shared_rendering_language": style_pack.get("asset_prompt_base", ""),
            "transparent_png_rules": "transparent background, no body copy, no logo, no QR code",
            "visual_text_rules": "only short concept phrases may become generated visual text",
            "negative_prompt": ", ".join(style_pack.get("do_not_use", [])),
        },
        "native_component_style": json.dumps(style_pack.get("native_component_skin", {}), ensure_ascii=False),
        "do_not_use": style_pack.get("do_not_use", []),
    }


def font_plan() -> dict[str, Any]:
    return {
        "cjk": "PingFang SC",
        "latin": "Aptos",
        "fallback": ["Microsoft YaHei", "Arial"],
        "hierarchy": {
            "title": "34-44pt editable title",
            "subtitle": "20-24pt editable argument",
            "body": "12-18pt editable body",
            "caption": "8-11pt utility captions",
            "data": "24-32pt editable key figures",
        },
        "display_text_policy": "Titles, body, numbers and execution details stay editable. Only short marked visual_text_assets may become raster assets.",
    }


def slide(
    n: int,
    title: str,
    purpose: str,
    content_type: str,
    mode: str,
    core: str,
    body: list[tuple[str, str]],
    *,
    component: str,
    role: str,
    structure: str,
    assets: list[dict[str, Any]] | None = None,
    visual_text: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "slide_number": n,
        "title": title,
        "page_purpose": purpose,
        "content_type": content_type,
        "page_mode": mode,
        "core_message": core,
        "editable_text": [
            {"id": "title", "text": title, "role": "page title"},
            *[
                {"id": f"item_{idx}", "text": text, "role": role_text}
                for idx, (role_text, text) in enumerate(body, start=1)
            ],
        ],
        "visual_text_assets": visual_text or [],
        "image_assets": assets or [],
        "locked_raster": [],
        "visual_design_role": role,
        "visual_anchors": ["layout recipe", "component skin", "asset slot"],
        "native_structure": structure,
        "component_preset": component,
        "layout_notes": "Fixture slide used to test reusable native PPT component behavior.",
        "speaker_notes": f"Fixture note for {title}.",
    }


def deck(name: str, deck_type: str, objective: str, slides: list[dict[str, Any]], style_pack: dict[str, Any]) -> dict[str, Any]:
    return {
        "deck_brief": {
            "project_name": name,
            "deck_type": deck_type,
            "audience": "brand and event decision makers",
            "objective": objective,
            "creative_summary": "Fixture blueprint for PPT Native Composer generalization testing.",
            "production_notes": "Generated by create_fixture_blueprints.py.",
        },
        "visual_bible": visual_bible(style_pack),
        "style_pack": style_pack,
        "font_plan": font_plan(),
        "slides": slides,
    }


def strategy_heavy(style_pack: dict[str, Any]) -> dict[str, Any]:
    slides = [
        slide(
            1,
            "Strategy Signal System",
            "Open a strategy-led proposal with a strong but editable cover.",
            "strategy cover",
            "full_image",
            "A single strategic signal gives the campaign a repeatable memory structure.",
            [("support line", "A strategy-heavy proposal fixture")],
            component="impact_cover",
            role="Hero Accent",
            structure="editable title plus large visual field",
            assets=[{"id": "kv_light_object", "type": "ai_png", "purpose": "cover signal object", "transparency": True}],
        ),
        slide(
            2,
            "Market Tension",
            "Show the strategic problem as a set of editable argument cards.",
            "strategy logic",
            "hybrid_native",
            "Audience attention is fragmented, but participation still follows recognizable triggers.",
            [
                ("Insight", "People remember a simple signal faster than a full campaign message."),
                ("Barrier", "Most event touchpoints are seen once and forgotten after exit."),
                ("Opportunity", "A repeated action can turn the signal into a social habit."),
            ],
            component="strategy_argument_cards",
            role="Structural Metaphor",
            structure="editable tension cards with one object anchor",
            assets=[{"id": "participation_object", "type": "ai_png", "purpose": "strategic metaphor object", "transparency": True}],
        ),
        slide(
            3,
            "Strategic Proposition",
            "Translate the argument into an editable proposition page.",
            "strategy proposition",
            "hybrid_native",
            "Build one signal that can be seen, repeated, collected, and shared.",
            [
                ("Seen", "The audience first recognizes the signal before the event."),
                ("Repeated", "The signal becomes a simple participation behavior."),
                ("Collected", "The action produces a tangible mission or proof."),
                ("Shared", "The proof becomes post-event social material."),
            ],
            component="strategy_argument_cards",
            role="Structural Metaphor",
            structure="editable proposition cards plus visual anchor",
            assets=[{"id": "participation_object", "type": "ai_png", "purpose": "participation object anchor", "transparency": True}],
        ),
        slide(
            4,
            "Decision Principles",
            "Test native data capsules for strategic decision principles.",
            "principle capsules",
            "template_native",
            "Every later execution choice must protect the same strategic signal.",
            [
                ("Principle 1", "One symbol, not multiple competing marks"),
                ("Principle 2", "One repeatable action, not a complex task"),
                ("Principle 3", "One social proof, not generic recap content"),
                ("Principle 4", "One measurable signal, not vague engagement"),
            ],
            component="data_capsules",
            role="Data Visual Skin",
            structure="editable principle capsules",
        ),
        slide(
            5,
            "Strategic Fit Matrix",
            "Test matrix handling for strategy-heavy content.",
            "strategy matrix",
            "template_native",
            "The proposal should pass both audience-value and brand-value filters.",
            [
                ("Audience Value", "Easy to understand before arrival"),
                ("Audience Value", "Rewarding to complete on site"),
                ("Audience Value", "Worth sharing after the event"),
                ("Brand Value", "Simple to recognize across channels"),
                ("Brand Value", "Reusable across event touchpoints"),
                ("Brand Value", "Measurable after the campaign"),
            ],
            component="benefit_matrix",
            role="Data Visual Skin",
            structure="editable strategic fit matrix",
        ),
    ]
    return deck("Fixture Strategy Heavy", "strategy-heavy proposal", "Test strategy-heavy editable deck structures.", slides, style_pack)


def execution_heavy(style_pack: dict[str, Any]) -> dict[str, Any]:
    slides = [
        slide(
            1,
            "Execution Operating System",
            "Open an execution-heavy proposal with editable title and visual system.",
            "execution cover",
            "full_image",
            "A clear operating system turns the idea into repeatable event behavior.",
            [("support line", "An execution-heavy proposal fixture")],
            component="impact_cover",
            role="Hero Accent",
            structure="editable title plus large visual field",
            assets=[{"id": "kv_light_object", "type": "ai_png", "purpose": "cover execution object", "transparency": True}],
        ),
        slide(
            2,
            "Participation Journey",
            "Test mechanism cards and integrated icon shelf.",
            "execution mechanism",
            "template_native",
            "The on-site journey must be simple enough to explain in one minute.",
            [
                ("Entry", "Scan the signal at the entrance gate."),
                ("Mission", "Collect a personalized mission card."),
                ("Action", "Complete the participation task."),
                ("Proof", "Receive and share the event proof."),
            ],
            component="execution_ticket_steps",
            role="Object-Based Layout",
            structure="editable mission-ticket process cards",
            assets=[{"id": "ticket_icon_system", "type": "ai_png", "purpose": "ticket icon strip", "transparency": True}],
        ),
        slide(
            3,
            "Site Flow Rhythm",
            "Test timeline behavior with operational phases.",
            "timeline execution",
            "template_native",
            "The flow should reduce waiting, distribute attention, and keep the signal visible.",
            [
                ("T-14", "Warm-up signal release"),
                ("T-7", "Mission preview and staff briefing"),
                ("Event", "Entry scan and on-site task flow"),
                ("T+1", "Recap content and reward release"),
            ],
            component="execution_timeline",
            role="Data Visual Skin",
            structure="editable operational timeline",
        ),
        slide(
            4,
            "Staff And Materials",
            "Test execution detail matrix for staffing and materials.",
            "execution matrix",
            "template_native",
            "Each touchpoint needs a clear owner, material, and fallback path.",
            [
                ("Audience Value", "Entrance signal board"),
                ("Audience Value", "Mission card desk"),
                ("Audience Value", "Reward collection counter"),
                ("Brand Value", "Staff briefing cards"),
                ("Brand Value", "Scanning backup plan"),
                ("Brand Value", "Content capture checklist"),
            ],
            component="benefit_matrix",
            role="Object-Based Layout",
            structure="editable staffing and materials matrix",
        ),
        slide(
            5,
            "Risk Control Points",
            "Test execution risk/control capsules.",
            "operations control",
            "template_native",
            "The operating system needs visible control points before production begins.",
            [
                ("Capacity", "Avoid single-point crowding at entry"),
                ("Clarity", "Keep instructions short and visible"),
                ("Backup", "Prepare manual mission-card handoff"),
                ("Capture", "Define who records each proof moment"),
            ],
            component="data_capsules",
            role="Data Visual Skin",
            structure="editable risk-control capsules",
        ),
    ]
    return deck("Fixture Execution Heavy", "execution-heavy proposal", "Test execution-heavy editable deck structures.", slides, style_pack)


def data_heavy(style_pack: dict[str, Any]) -> dict[str, Any]:
    slides = [
        slide(
            1,
            "Measurement Architecture",
            "Open a data-heavy proposal with editable title and visual system.",
            "data cover",
            "full_image",
            "The campaign should be measured as a sequence of signals, not a single vanity metric.",
            [("support line", "A data-heavy proposal fixture")],
            component="impact_cover",
            role="Hero Accent",
            structure="editable title plus large visual field",
            assets=[{"id": "kv_light_object", "type": "ai_png", "purpose": "cover measurement object", "transparency": True}],
        ),
        slide(
            2,
            "KPI Stack",
            "Test editable metric capsules.",
            "data capsules",
            "template_native",
            "The measurement model separates attention, action, proof, and amplification.",
            [
                ("Attention", "Signal views before event"),
                ("Action", "Mission scans and completions"),
                ("Proof", "Reward claims and shares"),
                ("Amplification", "Post-event content interactions"),
            ],
            component="data_capsules",
            role="Data Visual Skin",
            structure="editable KPI capsules",
        ),
        slide(
            3,
            "Channel Evidence",
            "Test hybrid data argument with visual anchor.",
            "data logic",
            "hybrid_native",
            "Each channel should have one job in the journey instead of repeating the same message.",
            [
                ("Pre-event", "Build recognition through signal exposure."),
                ("On-site", "Convert recognition into a mission action."),
                ("Post-event", "Turn proof into social memory."),
            ],
            component="strategy_argument_cards",
            role="Structural Metaphor",
            structure="editable channel evidence cards with visual anchor",
            assets=[{"id": "participation_object", "type": "ai_png", "purpose": "data signal anchor", "transparency": True}],
        ),
        slide(
            4,
            "Value Attribution Matrix",
            "Test data-heavy matrix with audience and brand outcomes.",
            "data matrix",
            "template_native",
            "Each measured behavior should map back to a useful audience or brand outcome.",
            [
                ("Audience Value", "Clear next action"),
                ("Audience Value", "Personalized reward path"),
                ("Audience Value", "Shareable proof asset"),
                ("Brand Value", "Attributable engagement point"),
                ("Brand Value", "Reusable social content"),
                ("Brand Value", "Post-event memory signal"),
            ],
            component="benefit_matrix",
            role="Data Visual Skin",
            structure="editable value attribution matrix",
        ),
        slide(
            5,
            "Reporting Rhythm",
            "Test timeline with measurement cadence.",
            "reporting timeline",
            "template_native",
            "The reporting cadence should follow the campaign rhythm rather than arrive only at the end.",
            [
                ("T-14", "Baseline signal exposure check"),
                ("T-1", "Pre-event action forecast"),
                ("Event", "Live participation readout"),
                ("T+7", "Post-event amplification review"),
            ],
            component="execution_timeline",
            role="Data Visual Skin",
            structure="editable reporting cadence timeline",
        ),
    ]
    return deck("Fixture Data Heavy", "data-heavy proposal", "Test data-heavy editable deck structures.", slides, style_pack)


FIXTURES = {
    "strategy_heavy": strategy_heavy,
    "execution_heavy": execution_heavy,
    "data_heavy": data_heavy,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", required=True, help="Output directory for blueprint JSON files.")
    parser.add_argument("--style-pack", default="editorial_event_signal", help="Base style pack key.")
    parser.add_argument("--fixture", choices=sorted(FIXTURES), action="append", help="Fixture to create. Defaults to all.")
    args = parser.parse_args()

    style_pack = load_style_pack(args.style_pack)
    selected = args.fixture or sorted(FIXTURES)
    outdir = Path(args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    for key in selected:
        data = FIXTURES[key](deepcopy(style_pack))
        path = outdir / f"{key}.json"
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
